 service: aws-catsup-node

 provider:
   name: aws
   runtime: nodejs14.x
   region: us-east-1

 functions:
   router:
     handler: handler.probot

     environment:
       # replace values with one\'s associated to your app
       APP_ID: ${ssm:APP_ID}
       PRIVATE_KEY: ${ssm:PRIVATE_KEY}
       WEBHOOK_SECRET: ${ssm:WEBHOOK_SECRET}
       LOG_FORMAT: json

     events:
       - http:
          path: /probot
          method: post
